#!/bin/bash

# git
alias gpr="git pull --rebase"
alias gpp="git pull --rebase && git push"

# system
alias ll="ls -la"
alias lal="ls -lA"
alias grep='grep --color=auto'
alias nocaps='/usr/bin/setxkbmap -layout us -option ctrl:nocaps'
alias blc='bosh -e lite -d cf'
alias python='python3'
alias pip='pip3'
alias flyl='fly -t log-cache'

# environments
alias lime='cd ~/workspace/log-cache-deployments/gcp/lime'
alias citron='cd ~/workspace/log-cache-deployments/gcp/citron'

# projects
alias src='cd ~/workspace/log-cache-release/src/code.cloudfoundry.org/log-cache'
alias glc="cd ~/workspace/go/src/code.cloudfoundry.org/go-log-cache"
alias tools="cd ~/workspace/go/src/github.com/log-cache-tools"
alias dotfiles="cd ~/workspace/log-cache-dotfiles"
alias lcr="cd ~/workspace/log-cache-release"
alias lc="cd ~/workspace/log-cache-release/src/code.cloudfoundry.org/log-cache"
alias lcd="cd ~/workspace/log-cache-deployments"
alias ci="cd ~/workspace/log-cache-ci"
alias lci="cd ~/workspace/log-cache-ci"
alias lcli="cd ~/workspace/go/src/code.cloudfoundry.org/log-cache-cli"
alias lcatsr="cd ~/workspace/log-cache-acceptance-tests-release"
alias lcats="cd ~/workspace/log-cache-acceptance-tests-release/src/code.cloudfoundry.org/log-cache-acceptance-tests"
alias lct="cd ~/workspace/go/src/github.com/cloudfoundry-incubator/log-cache-tools"
alias cfd='cd ~/workspace/cf-deployment'
alias cats="cd ~/workspace/go/src/github.com/cloudfoundry/cf-acceptance-tests"

# quick logins
alias login='./cf_login'
alias PWS='cf login -a api.run.pivotal.io -u cf-lamb@pivotallabs.com'
