#!/bin/bash

# git
alias gpr="git pull --rebase"
alias gpp="git pull --rebase && git push"
alias gs="git status"
alias gst="git status"
alias gl="git log --graph --oneline"

# system
alias ll="ls -la"
alias lal="ls -lA"
alias grep='grep --color=auto'
alias nocaps='/usr/bin/setxkbmap -layout us -option ctrl:nocaps'
alias blc='bosh -e lite -d cf'
alias python='python3'
alias pip='pip3'
alias flyd='fly -t cf-denver'
alias flyp='fly -t pws'

# projects
alias dotfiles="cd ~/workspace/metric-store-dotfiles; tmux_try_rename 'dotfiles'"
alias lcd="cd ~/workspace/metric-store-deployments; tmux_try_rename 'msd'"
alias cfd="cd ~/workspace/cf-deployment; tmux_try_rename 'cfd'"
alias cats="cd ~/workspace/go/src/github.com/cloudfoundry/cf-acceptance-tests; tmux_try_rename 'cats'"

alias msr="cd ~/workspace/oss/metric-store-release; tmux_try_rename 'ms'"
alias ms="cd ~/workspace/oss/metric-store-release; tmux_try_rename 'ms'"
alias osmr="cd ~/workspace/oss/metric-store-release; tmux_try_rename 'ms'"
alias osm="cd ~/workspace/oss/metric-store-release; tmux_try_rename 'ms'"
alias ci="cd ~/workspace/metric-store-ci; tmux_try_rename 'CI'"
alias mci="cd ~/workspace/metric-store-ci; tmux_try_rename 'CI'"
alias msd="cd ~/workspace/metric-store-deployments; tmux_try_rename 'msd'"

alias docs="cd ~/workspace/docs-metric-store; tmux_try_rename 'docs'"
alias book="cd ~/workspace/docs-book-metric-store; tmux_try_rename 'book'"

# quick logins
alias login='./cf_login'
alias pws='cf login -a api.run.pivotal.io -u cf-log-cache@pivotal.io'
alias prod_target='target_prod'

# wrappers
alias vim='nvim'
alias mvim='nvim'

alias pbcopy='DISPLAY=:1 xclip -selection c'

# tools
alias run_msats='~/workspace/metric-store-dotfiles/tools/run-oss-msats-against-yuzu.sh'

# Makes ./ work to reference the current package, e.g.,
# `gomvpkg -from ./foo -to ./bar`
function gomvpkg {
    command gomvpkg $(echo "$@" | sed -e "s, ./, ${PWD##$GOPATH/src/}/,g")
}
